version: '3.8'

services:
  bot:
    image: ghcr.io/workerspages/auto-delete-msg-bot:latest
    container_name: auto-delete-msg-bot
    restart: always
    # 设置时区
    environment:
      - TZ=Asia/Shanghai
      # ================= 配置区域 =================
      # 1. 你的机器人 Token
      - BOT_CONFIG=[{"token":"123456:AAA-机器人A","channels":[{"id":"-100111","delay":60},{"id":"-100222","delay":300}]},{"token":"987654:BBB-机器人B","channels":[{"id":"-100333","delay":10}]}]
      - DELETE_DELAY=120
      # ===========================================
    volumes:
      - ./auto_delete_bot.py:/app/auto_delete_bot.py
      # 挂载时间，确保日志时间正确
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    # 安装依赖并启动
    command: >
      sh -c "pip install pyTelegramBotAPI && python auto_delete_bot.py"
